version: 2

conda:
  environment: docs/environment.yaml

python:
  version: 3.6
  install:
    - method: pip
      path: .
      extra_requirements:
          - rtd

# default
# sphinx:
#   builder: html
#   configuration: conf.py
#   fail_on_warning: true
