# Usage: 
# $ conda env create -f conda_dev_env.yaml
# $ conda activate ipypublish_dev
# $ pip install --no-deps -e .
---
name: ipypublish_dev
channels:
- conda-forge
dependencies:
- python =3.6
- pip

- bibtexparser
- docutils
- jinja2
- jsonextended >=0.7
- jsonschema
- jupytext
- nbconvert
- nbformat
- ordered-set
- pandoc
- panflute
- ruamel.yaml
- setuptools
- six
- sphinx
- sphinxcontrib-bibtex
- texsoup <0.2
- tornado
- traitlets
# testing
- pytest >=3.6
- pytest-regressions
- nbsphinx
- pillow
- ipykernel
# style
- autopep8
- flake8 <3.8.0,>=3.7.0
- rope
- pre_commit =1.14.4
- yapf =0.26.0
# docs
- sphinx_rtd_theme
- jupyter
- matplotlib
- pandas
- sympy <1.3