---
jupyter:
  ipub:
    pandoc:
      convert_raw: true 
      at_notation: true
      use_numref: true
  jupytext:
    metadata_filter:
      notebook: ipub
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.6
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

.. _notebook_conversion:

# IPyPublish Basics

**This document is written in a Jupyter Notebook**
(or more precisely an RMarkdown version of the notebook),
which is executed and converted auto-magically to the page you are reading.
This is the power of IPyPublish!

```{python}
print("Hallo everybody!")
```

When analysing data with Python and Jupyter Notebooks, there are three 'modes'
we will be switching between:

- Writing and running analysis code (i.e. populating code cells)
- Documenting our analysis (i.e. populating markdown cells)
- Marking up and converting our notebooks to a distributable format

IPyPublish, in conjunction with some other great packages,
provides enhancements for working in each of these modes and the means to
seamlessly switch between them:

.. toctree::
    :maxdepth: 1

    code_cells
    markdown_cells
    nb_conversion


<!-- ## Setting up a Notebook

To take advantage of the above modes, we first need to add some additional -->